# s3-writer-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: s3-writer
  namespace: minio-tenant
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: models-writer
  AWS_SECRET_ACCESS_KEY: models-writer-password
